# Complete ISO 4217 currency list with flag emojis for better identification
CURRENCIES = {
    # Major currencies
    "USD": {"name": "US Dollar", "flag": "🇺🇸"},
    "EUR": {"name": "Euro", "flag": "🇪🇺"},
    "GBP": {"name": "British Pound", "flag": "🇬🇧"},
    "JPY": {"name": "Japanese Yen", "flag": "🇯🇵"},
    "AUD": {"name": "Australian Dollar", "flag": "🇦🇺"},
    "CAD": {"name": "Canadian Dollar", "flag": "🇨🇦"},
    "CHF": {"name": "Swiss Franc", "flag": "🇨🇭"},
    "CNY": {"name": "Chinese Yuan", "flag": "🇨🇳"},
    
    # Europe
    "SEK": {"name": "Swedish Krona", "flag": "🇸🇪"},
    "NOK": {"name": "Norwegian Krone", "flag": "🇳🇴"},
    "DKK": {"name": "Danish Krone", "flag": "🇩🇰"},
    "PLN": {"name": "Polish Zloty", "flag": "🇵🇱"},
    "CZK": {"name": "Czech Koruna", "flag": "🇨🇿"},
    "HUF": {"name": "Hungarian Forint", "flag": "🇭🇺"},
    "RON": {"name": "Romanian Leu", "flag": "🇷🇴"},
    "BGN": {"name": "Bulgarian Lev", "flag": "🇧🇬"},
    "HRK": {"name": "Croatian Kuna", "flag": "🇭🇷"},
    "ISK": {"name": "Icelandic Krona", "flag": "🇮🇸"},
    "RUB": {"name": "Russian Ruble", "flag": "🇷🇺"},
    "TRY": {"name": "Turkish Lira", "flag": "🇹🇷"},
    "UAH": {"name": "Ukrainian Hryvnia", "flag": "🇺🇦"},
    "ALL": {"name": "Albanian Lek", "flag": "🇦🇱"},
    "BAM": {"name": "Bosnia-Herzegovina Convertible Mark", "flag": "🇧🇦"},
    "MKD": {"name": "Macedonian Denar", "flag": "🇲🇰"},
    "RSD": {"name": "Serbian Dinar", "flag": "🇷🇸"},
    "MDL": {"name": "Moldovan Leu", "flag": "🇲🇩"},
    "BYN": {"name": "Belarusian Ruble", "flag": "🇧🇾"},
    
    # Asia Pacific
    "KRW": {"name": "South Korean Won", "flag": "🇰🇷"},
    "INR": {"name": "Indian Rupee", "flag": "🇮🇳"},
    "SGD": {"name": "Singapore Dollar", "flag": "🇸🇬"},
    "HKD": {"name": "Hong Kong Dollar", "flag": "🇭🇰"},
    "TWD": {"name": "New Taiwan Dollar", "flag": "🇹🇼"},
    "THB": {"name": "Thai Baht", "flag": "🇹🇭"},
    "MYR": {"name": "Malaysian Ringgit", "flag": "🇲🇾"},
    "IDR": {"name": "Indonesian Rupiah", "flag": "🇮🇩"},
    "PHP": {"name": "Philippine Peso", "flag": "🇵🇭"},
    "VND": {"name": "Vietnamese Dong", "flag": "🇻🇳"},
    "NZD": {"name": "New Zealand Dollar", "flag": "🇳🇿"},
    "PKR": {"name": "Pakistani Rupee", "flag": "🇵🇰"},
    "BDT": {"name": "Bangladeshi Taka", "flag": "🇧🇩"},
    "LKR": {"name": "Sri Lankan Rupee", "flag": "🇱🇰"},
    "MMK": {"name": "Myanmar Kyat", "flag": "🇲🇲"},
    "KHR": {"name": "Cambodian Riel", "flag": "🇰🇭"},
    "LAK": {"name": "Lao Kip", "flag": "🇱🇦"},
    "MNT": {"name": "Mongolian Tugrik", "flag": "🇲🇳"},
    "KZT": {"name": "Kazakhstani Tenge", "flag": "🇰🇿"},
    "UZS": {"name": "Uzbekistani Som", "flag": "🇺🇿"},
    "KGS": {"name": "Kyrgystani Som", "flag": "🇰🇬"},
    "TJS": {"name": "Tajikistani Somoni", "flag": "🇹🇯"},
    "TMT": {"name": "Turkmenistani Manat", "flag": "🇹🇲"},
    "AFN": {"name": "Afghan Afghani", "flag": "🇦🇫"},
    "NPR": {"name": "Nepalese Rupee", "flag": "🇳🇵"},
    "BTN": {"name": "Bhutanese Ngultrum", "flag": "🇧🇹"},
    "MVR": {"name": "Maldivian Rufiyaa", "flag": "🇲🇻"},
    
    # Middle East & Central Asia
    "AED": {"name": "UAE Dirham", "flag": "🇦🇪"},
    "SAR": {"name": "Saudi Riyal", "flag": "🇸🇦"},
    "QAR": {"name": "Qatari Riyal", "flag": "🇶🇦"},
    "KWD": {"name": "Kuwaiti Dinar", "flag": "🇰🇼"},
    "BHD": {"name": "Bahraini Dinar", "flag": "🇧🇭"},
    "OMR": {"name": "Omani Rial", "flag": "🇴🇲"},
    "ILS": {"name": "Israeli New Shekel", "flag": "🇮🇱"},
    "JOD": {"name": "Jordanian Dinar", "flag": "🇯🇴"},
    "LBP": {"name": "Lebanese Pound", "flag": "🇱🇧"},
    "SYP": {"name": "Syrian Pound", "flag": "🇸🇾"},
    "IQD": {"name": "Iraqi Dinar", "flag": "🇮🇶"},
    "IRR": {"name": "Iranian Rial", "flag": "🇮🇷"},
    "GEL": {"name": "Georgian Lari", "flag": "🇬🇪"},
    "AMD": {"name": "Armenian Dram", "flag": "🇦🇲"},
    "AZN": {"name": "Azerbaijani Manat", "flag": "🇦🇿"},
    
    # Africa
    "ZAR": {"name": "South African Rand", "flag": "🇿🇦"},
    "EGP": {"name": "Egyptian Pound", "flag": "🇪🇬"},
    "NGN": {"name": "Nigerian Naira", "flag": "🇳🇬"},
    "KES": {"name": "Kenyan Shilling", "flag": "🇰🇪"},
    "UGX": {"name": "Ugandan Shilling", "flag": "🇺🇬"},
    "TZS": {"name": "Tanzanian Shilling", "flag": "🇹🇿"},
    "ETB": {"name": "Ethiopian Birr", "flag": "🇪🇹"},
    "GHS": {"name": "Ghanaian Cedi", "flag": "🇬🇭"},
    "XOF": {"name": "West African CFA Franc", "flag": "🌍"},
    "XAF": {"name": "Central African CFA Franc", "flag": "🌍"},
    "MAD": {"name": "Moroccan Dirham", "flag": "🇲🇦"},
    "TND": {"name": "Tunisian Dinar", "flag": "🇹🇳"},
    "DZD": {"name": "Algerian Dinar", "flag": "🇩🇿"},
    "LYD": {"name": "Libyan Dinar", "flag": "🇱🇾"},
    "SDG": {"name": "Sudanese Pound", "flag": "🇸🇩"},
    "ZMW": {"name": "Zambian Kwacha", "flag": "🇿🇲"},
    "BWP": {"name": "Botswana Pula", "flag": "🇧🇼"},
    "NAD": {"name": "Namibian Dollar", "flag": "🇳🇦"},
    "SZL": {"name": "Eswatini Lilangeni", "flag": "🇸🇿"},
    "LSL": {"name": "Lesotho Loti", "flag": "🇱🇸"},
    "MZN": {"name": "Mozambican Metical", "flag": "🇲🇿"},
    "AOA": {"name": "Angolan Kwanza", "flag": "🇦🇴"},
    "MGA": {"name": "Malagasy Ariary", "flag": "🇲🇬"},
    "MUR": {"name": "Mauritian Rupee", "flag": "🇲🇺"},
    "SCR": {"name": "Seychellois Rupee", "flag": "🇸🇨"},
    "KMF": {"name": "Comorian Franc", "flag": "🇰🇲"},
    "DJF": {"name": "Djiboutian Franc", "flag": "🇩🇯"},
    "ERN": {"name": "Eritrean Nakfa", "flag": "🇪🇷"},
    "SOS": {"name": "Somali Shilling", "flag": "🇸🇴"},
    "RWF": {"name": "Rwandan Franc", "flag": "🇷🇼"},
    "BIF": {"name": "Burundian Franc", "flag": "🇧🇮"},
    "CDF": {"name": "Congolese Franc", "flag": "🇨🇩"},
    "XPF": {"name": "CFP Franc", "flag": "🏝️"},
    
    # Americas
    "BRL": {"name": "Brazilian Real", "flag": "🇧🇷"},
    "MXN": {"name": "Mexican Peso", "flag": "🇲🇽"},
    "ARS": {"name": "Argentine Peso", "flag": "🇦🇷"},
    "CLP": {"name": "Chilean Peso", "flag": "🇨🇱"},
    "COP": {"name": "Colombian Peso", "flag": "🇨🇴"},
    "PEN": {"name": "Peruvian Sol", "flag": "🇵🇪"},
    "UYU": {"name": "Uruguayan Peso", "flag": "🇺🇾"},
    "PYG": {"name": "Paraguayan Guarani", "flag": "🇵🇾"},
    "BOB": {"name": "Bolivian Boliviano", "flag": "🇧🇴"},
    "VES": {"name": "Venezuelan Bolívar", "flag": "🇻🇪"},
    "GYD": {"name": "Guyanese Dollar", "flag": "🇬🇾"},
    "SRD": {"name": "Surinamese Dollar", "flag": "🇸🇷"},
    "TTD": {"name": "Trinidad and Tobago Dollar", "flag": "🇹🇹"},
    "JMD": {"name": "Jamaican Dollar", "flag": "🇯🇲"},
    "BBD": {"name": "Barbadian Dollar", "flag": "🇧🇧"},
    "XCD": {"name": "East Caribbean Dollar", "flag": "🏝️"},
    "BSD": {"name": "Bahamian Dollar", "flag": "🇧🇸"},
    "BZD": {"name": "Belize Dollar", "flag": "🇧🇿"},
    "GTQ": {"name": "Guatemalan Quetzal", "flag": "🇬🇹"},
    "HNL": {"name": "Honduran Lempira", "flag": "🇭🇳"},
    "NIO": {"name": "Nicaraguan Córdoba", "flag": "🇳🇮"},
    "CRC": {"name": "Costa Rican Colón", "flag": "🇨🇷"},
    "PAB": {"name": "Panamanian Balboa", "flag": "🇵🇦"},
    "DOP": {"name": "Dominican Peso", "flag": "🇩🇴"},
    "HTG": {"name": "Haitian Gourde", "flag": "🇭🇹"},
    "CUP": {"name": "Cuban Peso", "flag": "🇨🇺"},
    
    # Oceania
    "FJD": {"name": "Fijian Dollar", "flag": "🇫🇯"},
    "TOP": {"name": "Tongan Paʻanga", "flag": "🇹🇴"},
    "WST": {"name": "Samoan Tālā", "flag": "🇼🇸"},
    "SBD": {"name": "Solomon Islands Dollar", "flag": "🇸🇧"},
    "VUV": {"name": "Vanuatu Vatu", "flag": "🇻🇺"},
    "PGK": {"name": "Papua New Guinea Kina", "flag": "🇵🇬"},
    
    # Special currencies
    "XAU": {"name": "Gold (troy ounce)", "flag": "🥇"},
    "XAG": {"name": "Silver (troy ounce)", "flag": "🥈"},
    "XPT": {"name": "Platinum (troy ounce)", "flag": "💍"},
    "XPD": {"name": "Palladium (troy ounce)", "flag": "⚪"},
}

def sorted_currency_codes():
    return sorted(CURRENCIES.keys())

def describe(code: str) -> str:
    currency = CURRENCIES.get(code, {"name": "Unknown", "flag": "❓"})
    flag = currency["flag"]
    name = currency["name"]
    return f"{flag} {code} - {name}"

def get_flag(code: str) -> str:
    currency = CURRENCIES.get(code, {"flag": "❓"})
    return currency["flag"]
